export enum ErrorCode {
  APP_ERROR = "APP_ERROR",
  AUTH_ERROR = "AUTH_ERROR",
  FORBIDDEN = "FORBIDDEN",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
